networks:
  cls_net:
    driver: bridge

x-common-config: &common-config
  environment:
    - LOG_LEVEL=info
  volumes:
    - ./tests/data:/var/classeq/data
  networks:
    - cls_net

services:
  api:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: classeq-api:latest
    container_name: classeq-api
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          cpus: 2.0
          memory: 800MB
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]
      interval: 10s
      timeout: 10s
      retries: 5

  watcher:
    # Inject all shared configs
    <<: *common-config

    # Service specific configs
    image: classeq-watcher:latest
    depends_on:
      - api
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: 4.0
          memory: 6GB
