api:
  #
  # The following settings are used to configure the API server
  #
  server:
    address: "0.0.0.0"
    port: 8080
    workers: 1

  #
  # The following settings are used to configure the API server related to the
  # file system
  #
  fs:
    serveDirectory: "/tmp/classeq-api/data"
    publicDirectory: "public"
    inputDirectory: "input"
    outputDirectory: "output"
    configFileName: "config.yaml"

  #
  # The following settings are used to configure the API server related to
  # models provisioning
  #
  models:
    - id: ce47d8bc-2885-3d2c-8247-5b8c8b28fefe
      name: "Tree 1"
    - id: ce47d8bc-2885-3d2c-8247-5b8c8b28fefa
      name: "Tree 2"
